### ISSUE TITLE
test failed "revert on Contract: Enigma        ...should fetch the worker params:

### ISSUE THREAD

**Issue by udibr** [enigmampc/enigma-contract#6]
enigma-contract udi$/usr/local/lib/node_modules/node/bin/darq-truffle test --network ganache
Using network 'ganache'.

Compiling ./contracts/Billionare.sol...
Compiling ./contracts/CoinMixer.sol...
Compiling ./contracts/Enigma.sol...
Compiling ./contracts/EnigmaToken.sol...
Compiling ./contracts/Migrations.sol...
Compiling ./contracts/utils/GetCode2.sol...
Compiling openzeppelin-solidity/contracts/ECRecovery.sol...
Compiling openzeppelin-solidity/contracts/math/SafeMath.sol...
Compiling openzeppelin-solidity/contracts/token/ERC20/BasicToken.sol...
Compiling openzeppelin-solidity/contracts/token/ERC20/ERC20.sol...
Compiling openzeppelin-solidity/contracts/token/ERC20/ERC20Basic.sol...
Compiling openzeppelin-solidity/contracts/token/ERC20/StandardToken.sol...

Compilation warnings encountered:

/Users/udi/Downloads/github/enigma-contract/contracts/Enigma.sol:430:10: Warning: Unused local variable.
        (uint256 b, uint256 seed, address[] memory workerArray) = getWorkersParams(blockNumber);
         ^-------^

using account 0xc44205c3aFf78e99049AfeAE4733a3481575CD26 as principal signer

  - ...testing simple abi encoding
  - ...testing dynamic encoding
  Contract: Enigma
setting principal node 0xc44205c3aFf78e99049AfeAE4733a3481575CD26
    ✓ ...should register a new worker (3308ms)
    ✓ ...should fetch worker details (205ms)
    ✓ ...should generate a taskId (109ms)
    ✓ ...should execute a computation task (308ms)
    ✓ ...should query computation tasks (78ms)
    - ...should commit the task results
    ✓ ...should set workers params (3016ms)
    1) ...should fetch the worker params
    > No events were emitted
    ✓ ...should select the worker 3 (419ms)
    - ...should verify the worker's signature and certificate
    ✓ ...should instantiate the Enigma class
    - ...should create a computation task from the enigma object
    - ...should dispatch a computation task and pay a fee

  enigma-utils
    ✓ ...should generate taskId
    ✓ ...should select worker
    - ...should verify worker
    ✓ ...should verify method signature
    ✓ ...should generate an Ethereum-like address from a public key
    ✓ ...should sign message with private key
044034127647bb7fdab7f1526c7d10be8b28174e2bba35b06ffd8a26fc2c20134a09e773199edc1ea792b150270ea3317689286c9fe239dd5b9c5cfd9e81b4b632
    ✓ ...should derive the right shared key same as in rust (39ms)
    ✓ ...should successfully encrypt the same as in rust
    ✓ ...should successfully decrypt the same as in rust

  16 passing (10s)
  7 pending
  1 failing

  1) Contract: Enigma
       ...should fetch the worker params:
     Error: Returned error: VM Exception while processing transaction: revert
      at Object.ErrorResponse (/usr/local/lib/node_modules/node/lib/node_modules/darq-truffle/build/webpack:/dependencies/truffle-contract/~/web3-core-helpers/src/errors.js:29:1)
      at /usr/local/lib/node_modules/node/lib/node_modules/darq-truffle/build/webpack:/dependencies/truffle-contract/~/web3/~/web3-core-requestmanager/src/index.js:140:1
      at /usr/local/lib/node_modules/node/lib/node_modules/darq-truffle/build/webpack:/dependencies/truffle-provider/wrapper.js:101:1
      at XMLHttpRequest.request.onreadystatechange (/usr/local/lib/node_modules/node/lib/node_modules/darq-truffle/build/webpack:/dependencies/truffle-provider/~/web3-providers-http/src/index.js:77:1)
      at XMLHttpRequestEventTarget.dispatchEvent (/usr/local/lib/node_modules/node/lib/node_modules/darq-truffle/build/webpack:/dependencies/truffle-provider/~/xhr2/lib/xhr2.js:64:1)
      at XMLHttpRequest._setReadyState (/usr/local/lib/node_modules/node/lib/node_modules/darq-truffle/build/webpack:/dependencies/truffle-provider/~/xhr2/lib/xhr2.js:354:1)
      at XMLHttpRequest._onHttpResponseEnd (/usr/local/lib/node_modules/node/lib/node_modules/darq-truffle/build/webpack:/dependencies/truffle-provider/~/xhr2/lib/xhr2.js:509:1)
      at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/node/lib/node_modules/darq-truffle/build/webpack:/dependencies/truffle-provider/~/xhr2/lib/xhr2.js:469:1)
      at endReadableNT (_stream_readable.js:1106:12)
      at process._tickCallback (internal/process/next_tick.js:178:19)

**Comment by elichai** [comment]
This issue was moved to enigmampc/enigma-contract-internal#2

**Comment by Isan-Rivkin** [comment]
From previous discussions of myself and @elichai we said that a contract must always have a state 0. 
Meaning, that deployment of bytecode comes together with the fact that there's some initial state. 
This should be reflected in the smart contract.

**Comment by elichai** [comment]
Yep. And I think only trusted enclaves can deploy a contract because there are 2 different bytecodes, and only the trusted enclave have access to the deployed working bytecode.

**Comment by Isan-Rivkin** [comment]
So in practice, that means that `hash(delta 0)` is part of  `secret contract deployment` process.

**Comment by apalepu23** [comment]
This sounds fine to us and the next update will reflect this initial state!

**Comment by Isan-Rivkin** [comment]
@apalepu23 We are working on this right now, could you at least write here how the signature will look like?

**Comment by lenak25** [comment]
@apalepu23 , any update on that?

**Comment by apalepu23** [comment]
hey! a couple questions on this that i think are rooted in this first question: after deployment of a contract, if you were to run `countStateDeltas`, what would you expect for this answer? 0 or 1?

**Comment by elichai** [comment]
@apalepu23  A newly deployed contract has an initial state(the constructor can edit the state). 
Meaning that the number of deltas is 1.
